import { Request, Response, NextFunction } from 'express';
type PartnerDocumentInput = {
    documentType: string;
    fileUrl?: string;
    fileName?: string;
    documentNumber?: string;
    nameOnDocument?: string;
    issueDate?: string | null;
    expiryDate?: string | null;
    submittedNote?: string;
};
type OnboardingProfileInput = {
    ownerName?: string | undefined;
    businessName?: string | undefined;
    partnerType?: string | undefined;
    primaryContact?: string | undefined;
    alternateMobile?: string | undefined;
    whatsappNumber?: string | undefined;
    email?: string | undefined;
    state?: string | undefined;
    district?: string | undefined;
    city?: string | undefined;
    pinCode?: string | undefined;
    businessAddress?: string | undefined;
    googleMapsLocation?: string | undefined;
    businessDescription?: string | undefined;
    businessExperience?: string | undefined;
    expectedMonthlyListings?: number | string | undefined;
    serviceAreas?: string | undefined;
    workingHours?: string | undefined;
    gstNumber?: string | undefined;
    businessRegistrationNumber?: string | undefined;
    websiteUrl?: string | undefined;
    socialLinks?: string | undefined;
    yearsInBusiness?: number | string | undefined;
    teamSize?: number | string | undefined;
    contactPreference?: string | undefined;
    referralCode?: string | undefined;
};
export declare const ensurePartnerProfileForUser: (user: {
    id: string;
    role?: string | null;
    name?: string | null;
    email?: string | null;
}) => Promise<any>;
export declare const buildAuthUserPayload: (user: any) => Promise<{
    id: any;
    email: any;
    name: any;
    role: string;
    rawRole: any;
    status: any;
    mobile: any;
    whatsappNumber: any;
    city: any;
    state: any;
    isPrimeCustomer: boolean;
    customerCategory: import("../utils/customerPrime").PrimeCustomerCategory;
    primeSubscriptionExpiresAt: Date | null;
    createdAt: any;
    updatedAt: any;
} | {
    id: any;
    email: any;
    name: any;
    role: string;
    rawRole: any;
    status: any;
    mobile: any;
    whatsappNumber: any;
    city: any;
    state: any;
    isPrimeCustomer: boolean;
    customerCategory: import("../utils/customerPrime").PrimeCustomerCategory;
    primeSubscriptionExpiresAt: Date | null;
    createdAt: any;
    updatedAt: any;
    permissions: string[];
    title: any;
    isRootAdmin: any;
} | {
    id: any;
    email: any;
    name: any;
    role: string;
    rawRole: any;
    status: any;
    mobile: any;
    whatsappNumber: any;
    city: any;
    state: any;
    isPrimeCustomer: boolean;
    customerCategory: import("../utils/customerPrime").PrimeCustomerCategory;
    primeSubscriptionExpiresAt: Date | null;
    createdAt: any;
    updatedAt: any;
    permissions: any;
    customRoleId: any;
    customRoleName: any;
    title: any;
    isRootAdmin: any;
} | {
    id: any;
    email: any;
    role: string;
    rawRole: any;
    status: any;
    isPrimeCustomer: boolean;
    customerCategory: import("../utils/customerPrime").PrimeCustomerCategory;
    primeSubscriptionExpiresAt: Date | null;
    createdAt: any;
    updatedAt: any;
    name: any;
    ownerName: any;
    onboardingStatus: any;
    accountStatus: any;
    kycStatus: any;
    partnerType: any;
    businessAddress: any;
    district: any;
    pinCode: any;
    contactPreference: any;
    city: any;
    state: any;
    mobile: any;
    whatsappNumber: any;
    isVerifiedPartner: boolean;
    portalHomeRoute: string | null;
}>;
export declare const getPartnerOnboardingContext: (userId: string) => Promise<any>;
export declare const buildOnboardingResponse: (partnerUser: any) => {
    profile: {
        ownerName: any;
        businessName: any;
        partnerType: any;
        primaryContact: any;
        alternateMobile: any;
        whatsappNumber: any;
        email: any;
        state: any;
        district: any;
        city: any;
        pinCode: any;
        businessAddress: any;
        googleMapsLocation: any;
        businessDescription: any;
        businessExperience: any;
        expectedMonthlyListings: any;
        serviceAreas: any;
        workingHours: any;
        gstNumber: any;
        businessRegistrationNumber: any;
        websiteUrl: any;
        socialLinks: any;
        yearsInBusiness: any;
        teamSize: any;
        contactPreference: any;
        referralCode: any;
    };
    requiredDocuments: import(".prisma/client").$Enums.KycDocumentType[];
    kycDocuments: any;
    agreements: {
        agreementType: "COMMISSION_POLICY" | "CUSTOMER_DATA_USAGE" | "FRAUD_POLICY" | "LISTING_AUTHENTICITY" | "MARKETPLACE_TERMS" | "MEDIA_OWNERSHIP" | "PARTNER_TERMS";
        checked: boolean;
    }[];
    reviewHistory: any;
    progress: {
        profileComplete: boolean;
        documentsComplete: boolean;
        agreementsComplete: boolean;
        readyForSubmission: boolean;
    };
};
export declare const saveOnboardingData: ({ userId, userEmail, profile, kycDocuments, agreementTypes, submitForReview, preserveApprovalState, actionName, actionComment, }: {
    userId: string;
    userEmail?: string | null;
    profile: OnboardingProfileInput;
    kycDocuments: PartnerDocumentInput[];
    agreementTypes: string[];
    submitForReview: boolean;
    preserveApprovalState?: boolean;
    actionName?: string;
    actionComment?: string;
}) => Promise<void>;
export declare const register: (req: Request, res: Response, next: NextFunction) => Promise<Response<any, Record<string, any>> | undefined>;
export declare const login: (req: Request, res: Response, next: NextFunction) => Promise<Response<any, Record<string, any>> | undefined>;
export declare const getMobileOtpConfig: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const sendLoginOtp: (req: Request, res: Response, next: NextFunction) => Promise<Response<any, Record<string, any>> | undefined>;
export declare const verifyLoginOtp: (req: Request, res: Response, next: NextFunction) => Promise<Response<any, Record<string, any>> | undefined>;
export declare const checkSetup: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const getGoogleClientConfig: (req: Request, res: Response, next: NextFunction) => Promise<void>;
export declare const googleLogin: (req: Request, res: Response, next: NextFunction) => Promise<Response<any, Record<string, any>> | undefined>;
export declare const getProfile: (req: Request, res: Response, next: NextFunction) => Promise<Response<any, Record<string, any>> | undefined>;
export declare const getCustomerPrimeAccess: (req: Request, res: Response, next: NextFunction) => Promise<Response<any, Record<string, any>> | undefined>;
export declare const submitCustomerPrimeSubscription: (req: Request, res: Response, next: NextFunction) => Promise<Response<any, Record<string, any>> | undefined>;
export declare const updateProfile: (req: Request, res: Response, next: NextFunction) => Promise<Response<any, Record<string, any>> | undefined>;
export declare const updatePassword: (req: Request, res: Response, next: NextFunction) => Promise<Response<any, Record<string, any>> | undefined>;
export declare const getPartnerOnboarding: (req: Request, res: Response, next: NextFunction) => Promise<Response<any, Record<string, any>> | undefined>;
export declare const savePartnerOnboarding: (req: Request, res: Response, next: NextFunction) => Promise<Response<any, Record<string, any>> | undefined>;
export declare const submitPartnerOnboarding: (req: Request, res: Response, next: NextFunction) => Promise<Response<any, Record<string, any>> | undefined>;
export declare const submitKyc: typeof submitPartnerOnboarding;
export {};
//# sourceMappingURL=auth.controller.d.ts.map