"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_controller_1 = require("../controllers/auth.controller");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const router = (0, express_1.Router)();
router.get('/setup-status', auth_controller_1.checkSetup);
router.get('/google-config', auth_controller_1.getGoogleClientConfig);
router.get('/mobile-otp/config', auth_controller_1.getMobileOtpConfig);
router.post('/register', auth_controller_1.register);
router.post('/login', auth_controller_1.login);
router.post('/login/mobile-otp/send', auth_controller_1.sendLoginOtp);
router.post('/login/mobile-otp/verify', auth_controller_1.verifyLoginOtp);
router.post('/google', auth_controller_1.googleLogin);
router.get('/profile', auth_middleware_1.requireAuth, auth_controller_1.getProfile);
router.patch('/profile', auth_middleware_1.requireAuth, auth_controller_1.updateProfile);
router.patch('/profile/password', auth_middleware_1.requireAuth, auth_controller_1.updatePassword);
router.get('/customer-prime/access', auth_middleware_1.requireAuth, auth_controller_1.getCustomerPrimeAccess);
router.post('/customer-prime/subscribe', auth_middleware_1.requireAuth, auth_controller_1.submitCustomerPrimeSubscription);
router.get('/partner/onboarding', auth_middleware_1.requireAuth, auth_controller_1.getPartnerOnboarding);
router.put('/partner/onboarding', auth_middleware_1.requireAuth, auth_controller_1.savePartnerOnboarding);
router.post('/partner/onboarding/submit', auth_middleware_1.requireAuth, auth_controller_1.submitPartnerOnboarding);
router.post('/partner/kyc', auth_middleware_1.requireAuth, auth_controller_1.submitKyc);
exports.default = router;
//# sourceMappingURL=auth.routes.js.map