"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const document_controller_1 = require("../controllers/document.controller");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const documentUpload_1 = require("../utils/documentUpload");
const router = (0, express_1.Router)();
const secureUpload = (0, documentUpload_1.getDocumentUploadMiddleware)('secure');
const publicUpload = (0, documentUpload_1.getDocumentUploadMiddleware)('public');
const publicListingMediaUpload = (0, documentUpload_1.getDocumentUploadMiddleware)('public', 'listing-media');
const publicFinanceSupportUpload = (0, documentUpload_1.getDocumentUploadMiddleware)('public', 'finance-support');
const publicHeroImageUpload = (0, documentUpload_1.getDocumentUploadMiddleware)('public', 'hero-image');
const publicInspectionSectionUpload = (0, documentUpload_1.getDocumentUploadMiddleware)('public', 'inspection-section');
router.post('/upload/secure', auth_middleware_1.requireAuth, auth_middleware_1.requirePortalOperator, secureUpload.single('file'), document_controller_1.uploadSecureDocument);
router.post('/upload/public', auth_middleware_1.requireAuth, auth_middleware_1.requirePortalOperator, publicUpload.single('file'), document_controller_1.uploadPublicDocument);
router.post('/upload/public/customer-prime-receipt', auth_middleware_1.requireAuth, publicUpload.single('file'), document_controller_1.uploadCustomerPrimeReceipt);
router.post('/upload/public/finance-support', auth_middleware_1.requireAuth, auth_middleware_1.requirePortalOperator, publicFinanceSupportUpload.single('file'), document_controller_1.uploadPublicFinanceSupportImage);
router.post('/upload/public/hero-image', auth_middleware_1.requireAuth, auth_middleware_1.requirePortalOperator, publicHeroImageUpload.single('file'), document_controller_1.uploadPublicHeroImage);
router.post('/upload/public/inspection-section', auth_middleware_1.requireAuth, auth_middleware_1.requirePortalOperator, publicInspectionSectionUpload.single('file'), document_controller_1.uploadPublicInspectionSectionImage);
router.post('/upload/public/listing-media', auth_middleware_1.requireAuth, publicListingMediaUpload.single('file'), document_controller_1.uploadPublicListingMedia);
router.get('/secure/:filename', auth_middleware_1.requireAuth, auth_middleware_1.requirePortalOperator, document_controller_1.getSecureDocument);
exports.default = router;
//# sourceMappingURL=document.routes.js.map