"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const master_controller_1 = require("../controllers/master.controller");
const translation_controller_1 = require("../controllers/translation.controller");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const router = (0, express_1.Router)();
router.get('/categories', auth_middleware_1.requireAuth, master_controller_1.getCategories);
router.post('/categories', auth_middleware_1.requireAuth, (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['categories.create']), master_controller_1.createCategory);
router.put('/categories/:id', auth_middleware_1.requireAuth, (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['categories.update']), master_controller_1.updateCategory);
router.delete('/categories/:id', auth_middleware_1.requireAuth, (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['categories.delete']), master_controller_1.deleteCategory);
router.get('/brands', auth_middleware_1.requireAuth, master_controller_1.getBrands);
router.post('/brands', auth_middleware_1.requireAuth, (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['brands.create']), master_controller_1.createBrand);
router.put('/brands/:id', auth_middleware_1.requireAuth, (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['brands.update']), master_controller_1.updateBrand);
router.delete('/brands/:id', auth_middleware_1.requireAuth, (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['brands.delete']), master_controller_1.deleteBrand);
router.get('/models/:brandId', master_controller_1.getModels);
router.get('/icons', auth_middleware_1.requireAuth, auth_middleware_1.requirePortalOperator, master_controller_1.getIcons);
router.post('/icons', master_controller_1.createIcon);
router.get('/dealers', master_controller_1.getApprovedDealers);
router.get('/dealers/:id', master_controller_1.getDealerById);
router.get('/dealers/:id/listings', master_controller_1.getDealerListings);
router.get('/finance-support', master_controller_1.getFinanceSupportItems);
router.get('/hero-image', master_controller_1.getHeroImage);
router.get('/inspection-section', master_controller_1.getInspectionSection);
router.get('/translations', translation_controller_1.getTranslationOverrides);
router.post('/translations/register-missing', translation_controller_1.registerMissingTranslationKeys);
router.get('/public-listings', master_controller_1.getPublicListings);
router.get('/public-listings/:id', master_controller_1.getPublicListingById);
router.post('/public-listings/:id/view', master_controller_1.incrementListingView);
router.get('/public-categories', master_controller_1.getPublicCategories);
router.get('/public-search-filters', master_controller_1.getPublicSearchFilters);
router.get('/recent-listings', master_controller_1.getRecentListings);
exports.default = router;
//# sourceMappingURL=master.routes.js.map