"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const admin_controller_1 = require("../controllers/admin.controller");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const role_controller_1 = require("../controllers/role.controller");
const router = (0, express_1.Router)();
router.use(auth_middleware_1.requireAuth);
const canViewDashboard = (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['dashboard.view']);
const canManageSettings = (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['settings.manage']);
const canManageRecurrence = (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['recurrence.manage']);
const canViewUsers = (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['users.read']);
const canCreateUsers = (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['users.create']);
const canUpdateUsers = (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['users.update']);
const canDeleteUsers = (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['users.delete']);
const canViewRoles = (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['roles.read']);
const canCreateRoles = (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['roles.create']);
const canUpdateRoles = (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['roles.update']);
const canDeleteRoles = (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['roles.delete']);
const canViewPartners = (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['partners.read']);
const canCreatePartners = (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['partners.create']);
const canUpdatePartners = (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['partners.update']);
const canDeletePartners = (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['partners.delete']);
const canManageVerifications = (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['kyc.manage']);
const canManageEnquiries = (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['enquiries.manage']);
const canViewVisitors = (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['visitors.read']);
const canUpdateAccountStatus = (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['users.update', 'partners.change_status', 'visitors.change_status']);
const canManageCategories = (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['categories.read', 'categories.create', 'categories.update', 'categories.delete']);
const canManageListings = (0, auth_middleware_1.requireSuperAdminOrEmployeePermissions)(['partners.read', 'kyc.manage', 'listings.read']);
router.get('/dashboard', canViewDashboard, admin_controller_1.getDashboardSummary);
router.get('/badges', canViewDashboard, admin_controller_1.getModuleBadges);
router.get('/finance-support', canManageSettings, admin_controller_1.getFinanceSupportContent);
router.put('/finance-support', canManageSettings, admin_controller_1.updateFinanceSupportContent);
router.get('/hero-image', canManageSettings, admin_controller_1.getHeroImageContent);
router.put('/hero-image', canManageSettings, admin_controller_1.updateHeroImageContent);
router.get('/inspection-section', canManageSettings, admin_controller_1.getInspectionSectionContent);
router.put('/inspection-section', canManageSettings, admin_controller_1.updateInspectionSectionContent);
router.get('/settings', canManageSettings, admin_controller_1.getPlatformSettings);
router.patch('/settings', canManageSettings, admin_controller_1.updatePlatformSettings);
router.get('/customer-prime-payments', canManageRecurrence, admin_controller_1.getCustomerPrimePayments);
router.patch('/customer-prime-payments/:id/status', canManageRecurrence, admin_controller_1.updateCustomerPrimePaymentStatus);
router.get('/users', canViewUsers, admin_controller_1.getAdminUsers);
router.get('/partners', canViewPartners, admin_controller_1.getAdminPartners);
router.get('/visitors', canViewVisitors, admin_controller_1.getCustomerVisitors);
router.post('/users', canCreateUsers, admin_controller_1.createManagedUser);
router.post('/partners', canCreatePartners, admin_controller_1.createPartnerUser);
router.patch('/users/:id', canUpdateUsers, admin_controller_1.updateManagedUserAccount);
router.patch('/users/:id/password', canUpdateUsers, admin_controller_1.resetManagedUserPassword);
router.delete('/users/:id', canDeleteUsers, admin_controller_1.deleteManagedUser);
router.get('/partners/:id/onboarding', canViewPartners, admin_controller_1.getAdminPartnerOnboarding);
router.put('/partners/:id/onboarding', canUpdatePartners, admin_controller_1.saveAdminPartnerOnboarding);
router.post('/partners/:id/onboarding/submit', canUpdatePartners, admin_controller_1.submitAdminPartnerOnboarding);
router.get('/verifications', canManageVerifications, admin_controller_1.getPendingVerifications);
router.get('/verifications/:id', canManageVerifications, admin_controller_1.getVerificationDetail);
router.get('/listings', canManageListings, admin_controller_1.getAdminListings);
router.patch('/verifications/:id/status', canManageVerifications, admin_controller_1.updateVerificationStatus);
router.patch('/listings/:id/status', canManageListings, admin_controller_1.updateAdminListingStatus);
router.patch('/users/:id/status', canUpdateAccountStatus, admin_controller_1.updateAdminUserStatus);
router.patch('/partners/:id', canUpdatePartners, admin_controller_1.updatePartnerUser);
router.delete('/partners/:id', canDeletePartners, admin_controller_1.deletePartnerUser);
// Custom Roles
router.get('/roles', canViewRoles, role_controller_1.getRoles);
router.post('/roles', canCreateRoles, role_controller_1.createRole);
router.patch('/roles/:id', canUpdateRoles, role_controller_1.updateRole);
router.delete('/roles/:id', canDeleteRoles, role_controller_1.deleteRole);
exports.default = router;
//# sourceMappingURL=superadmin.routes.js.map