import multer from 'multer';
export type UploadVisibility = 'public' | 'secure';
export type UploadPurpose = 'document' | 'listing-media' | 'finance-support' | 'hero-image' | 'inspection-section';
export declare const MAX_DOCUMENT_UPLOAD_SIZE: number;
export declare const MAX_LISTING_VIDEO_UPLOAD_SIZE: number;
export declare const MAX_FINANCE_SUPPORT_IMAGE_UPLOAD_SIZE: number;
export declare const MAX_HERO_IMAGE_UPLOAD_SIZE: number;
export declare const MAX_INSPECTION_SECTION_IMAGE_UPLOAD_SIZE: number;
export declare const uploadRootDir: string;
export declare const publicUploadDir: string;
export declare const secureUploadDir: string;
export declare const publicListingMediaUploadDir: string;
export declare const publicFinanceSupportUploadDir: string;
export declare const publicHeroImageUploadDir: string;
export declare const publicInspectionSectionUploadDir: string;
export declare const ensureUploadDirectories: () => void;
export declare const isAllowedDocumentFile: (mimeType: string, originalName: string) => boolean;
export declare const isAllowedListingMediaFile: (mimeType: string, originalName: string) => boolean;
export declare const isAllowedFinanceSupportImageFile: (mimeType: string, originalName: string) => boolean;
export declare const getDocumentUploadMiddleware: (visibility: UploadVisibility, purpose?: UploadPurpose) => multer.Multer;
export declare const isPdfMimeType: (mimeType?: string | null) => mimeType is "application/pdf";
export declare const isVideoMimeType: (mimeType?: string | null) => mimeType is "video/mp4" | "video/quicktime" | "video/webm";
export declare const getSecureDocumentUrl: (fileName: string) => string;
export declare const getPublicDocumentUrl: (fileName: string) => string;
export declare const getPublicListingMediaUrl: (fileName: string) => string;
export declare const getPublicFinanceSupportImageUrl: (fileName: string) => string;
export declare const getPublicHeroImageUrl: (fileName: string) => string;
export declare const getPublicInspectionSectionImageUrl: (fileName: string) => string;
//# sourceMappingURL=documentUpload.d.ts.map